language: python
matrix:
    include:
        - python: "3.6"
          env: TOXENV=lint
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.8"
          env: TOXENV=py38
        - python: "3.9"
          env: TOXENV=py39

install:
    - travis_retry pip install -U pip setuptools tox
    - travis_retry pip install -U coverage coveralls

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls

notifications:
    email: false

cache:
  pip: true
  directories:
    - eggs/
